lu_residence_webapp/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('news/', views.news, name='news'),
    path('apply/', views.apply, name='apply'),
    path('faq/', views.faq, name='faq'),
    path('fees/', views.fees, name='fees'),
    path('register/', views.register, name='register'),
    path('housing/', views.housing, name='housing'),
    path('workorder/', views.work_order, name='work_order'),
    path('workorder/bartley/', views.bartley, name='workorder_bartley'),
    path('workorder/north_res/', views.north_res, name='workorder_northres'),
    path('workorder/south_res/', views.south_res, name='workorder_southres'),
    path('workorder/townhouse/', views.repair_form, name='workorder_townhouse'),
]

lu_residence_webapp/lu_residence_webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

lu_residence_webapp/home/models.py
from django.db import models


# Create your models here.

lu_residence_webapp/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def landing(request):
    return render(request, '../../common/templates/home/landing.html')


def news(request):
    return render(request, '../../common/templates/home/news.html')


def housing(request):
    return render(request, '../../common/templates/home/housing.html')


def fees(request):
    return render(request, '../../common/templates/fees/fees.html')


def work_order(request):
    return render(request, '../../common/templates/workorder/workorder.html')


def repair_form(request):
    return render(request, '../../common/templates/workorder/townhouse_repair.html')


def bartley(request):
    return render(request, '../../common/templates/workorder/bartley.html')


def north_res(request):
    return render(request, '../../common/templates/workorder/north_residence.html')


def south_res(request):
    return render(request, '../../common/templates/workorder/south_residence.html')


def faq(request):
    return render(request, '../../common/templates/faq/faq.html')
def apply(request):
    return render(request, '../../common/templates/apply/apply.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home:news')
    else:
        form = UserCreationForm()
    return render(request, '../../common/templates/registration/register.html', {'form': form})

lu_residence_webapp/lu_residence_webapp/views.py
from django.shortcuts import render, redirect


def home(request):
    return redirect('home:landing')

lu_residence_webapp/common/templates/apply/apply.html
{% extends "base.html" %}
{% load static %}

{% block title %}Residence News{% endblock %}

{% block intro %}
    Apply
{% endblock %}

{% block content %}
   
<head>

<style>
    .tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: #555;
  color: #fff;
  text-align: center;
  padding: 5px 0;
  border-radius: 6px;

  /* Position the tooltip text */
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -60px;

  /* Fade in tooltip */
  opacity: 0;
  transition: opacity 0.3s;
}

/* Tooltip arrow */
.tooltip .tooltiptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

/* Show the tooltip text when you mouse over the tooltip container */
.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}
   
    h1{
        text-align: center;
        align-content: center;
        padding bottom: 12px;
        color:#3267a8; 
    }    
h2{
 font-family: Sans-serif; 
 font-size: 24px;     
 font-style: normal; 
 font-weight: bold; 
 color: black;
 text-align: center; 
 text-decoration: underline
}
table{
 font-family: verdana; 
 color:#3267a8; 
 font-size: 16px; 
 font-style: normal;
 font-weight: bold;
 background: transparent;
 border-collapse: collapse; 
 border: 4px solid #000000;
 border-style:hidden;
    width: 90%;
  
}
table.inner{
 border: 10px
}
input[type=text], input[type=email], input[type=number]{
 width: 50%;
 padding: 6px 12px;
 margin: 5px 0;
 box-sizing: border-box;
}
input[type=submit], input[type=reset]{
 width: 15%;
 padding: 8px 12px;
 margin: 5px 0;
 box-sizing: border-box;
    }
    $(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip.right();
       
}
});

</style>
</head>


    <h1>Apply for Residence</h1>

    
<table align="center" cellpadding = "10">

<!--------------------- First Name ------------------------------------------>
<tr>
<td>First Name</td>
<td><input type="text" name="FirstName" maxlength="50" placeholder="First Name" />
(Max 50 Characters Allowed)
</td>
</tr>
<!------------------------ Last Name --------------------------------------->
<tr>
<td>Last Name</td>
<td><input type="text" name="LastName" maxlength="50" placeholder="Last Name"/>
(Max 50 Characters Allowed)
</td>
</tr>
<!-------------------------- Email ID ------------------------------------->
<tr>
<td>Email ID</td>
<td><input type="email" name="EmailID" maxlength="100" placeholder="@lakeheadu.ca"/></td>
</tr>
<!-------------------------- Mobile Number ------------------------------------->
<tr>
<td>Mobile Number</td>
<td>
<input type="text" name="MobileNumber" maxlength="11" placeholder="+639"/>
(11 Digits Allowed)
</td>
</tr>
<!---------------------- Gender ------------------------------------->
<tr>
<td>Gender</td>
<td>
<input type="radio" name="Gender" value="Male" />
Male
<input type="radio" name="Gender" value="Female" />
Female
</td>
</tr>
<!--------------------------Date Of Birth----------------------------------->
<tr>
<td>Date of Birth(DOB)</td>
<td>
<select name="BirthDay" id="Birthday_Day">
<option value="-1">Day:</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select>
<select name="BirthdayMonth" id="Birthday_Month">
<option value="-1">Month:</option>
<option value="January">Jan(1)</option>
<option value="February">Feb(2)</option>
<option value="March">Mar(3)</option>
<option value="April">Apr(4)</option>
<option value="May">May(5)</option>
<option value="June">Jun(6)</option>
<option value="July">Jul(7)</option>
<option value="August">Aug(8)</option>
<option value="September">Sep(9)</option>
<option value="October">Oct(10)</option>
<option value="November">Nov(11)</option>
<option value="December">Dec(12)</option>
</select>
<select name="BirthdayYear" id="Birthday_Year">
<option value="-1">Year:</option>
<option value="2019">2021</option>
<option value="2019">2020</option>
<option value="2019">2019</option>
<option value="2018">2018</option>
<option value="2017">2017</option>
<option value="2016">2016</option>
<option value="2015">2015</option>
<option value="2014">2014</option>
<option value="2013">2013</option>
<option value="2012">2012</option>
<option value="2011">2011</option>
<option value="2010">2010</option>
<option value="2009">2009</option>
<option value="2008">2008</option>
<option value="2007">2007</option>
<option value="2006">2006</option>
<option value="2005">2005</option>
<option value="2004">2004</option>
<option value="2003">2003</option>
<option value="2002">2002</option>
<option value="2001">2001</option>
<option value="2000">2000</option>
<option value="1999">1999</option>
<option value="1998">1998</option>
<option value="1997">1997</option>
<option value="1996">1996</option>
<option value="1995">1995</option>
<option value="1994">1994</option>
<option value="1993">1993</option>
<option value="1992">1992</option>
<option value="1991">1991</option>
<option value="1990">1990</option>
<option value="1989">1989</option>
<option value="1988">1988</option>
<option value="1987">1987</option>
<option value="1986">1986</option>
<option value="1985">1985</option>
<option value="1984">1984</option>
<option value="1983">1983</option>
<option value="1982">1982</option>
<option value="1981">1981</option>
<option value="1980">1980</option>
</select>
</td>
</tr>


<tr>
    
<td>Select the Residence <br /><br /><br /></td>
<td>
<br/>
    
    
 <a href="#" data-toggle="tooltip" abbr title="Standard Townhouse
Accessible Townhouse"><input type="radio" name="Select" value="Town House" /></a>
<a href="#" data-toggle="tooltip" abbr title="Standard Townhouse
Accessible Townhouse">Townhouses</a><br>
<a href="#" data-toggle="tooltip" abbr title="Bartley Residence
Halliday Hall Residence
Prettie Residence"><input type="radio" name="Select" value="Residence Halls" /></a>
<a href="#" data-toggle="tooltip" abbr title="Bartley Residence
Halliday Hall Residence
Prettie Residence">Residence Halls</a><br/>
<a href="#" data-toggle="tooltip" abbr title="Standard apartment Unit
Barrier Free Apartment Unit"><input type="radio" name="Select" value="Apartments" /></a>
<a href="#" data-toggle="tooltip" abbr title="Standard apartment Unit
Barrier Free Apartment Unit">Apartments</a><br/>

</td>
</tr>


<tr>
<td colspan="2" align="center">
<input class="btn btn-primary"  type="submit" value="Submit">
<input class="btn btn-danger" type="reset" value="Reset">
</td>
</tr>
</table>
</body>
{% endblock %}

lu_residence_webapp/common/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href={% static "bootstrap/css/bootstrap.min.css" %}>
    <link rel="stylesheet" href="{% static "styles/base.css" %}">
    <title>{% block title %}CHMSC Residence{% endblock %}</title>
</head>

<body>

    <div role="banner" id="top">
        <div class="container-fluid" >
            <a class="logo" href="{% url 'home:news' %}">
                <img src="{% static "images/chmsc.jpg" %}" alt="Lakehead logo" width="70" height="70">
            </a>
            <p class="meta">CHMSC Residence</p>

            <div role="navigation" class="container-fluid" id="nav-links">
                {% if user.is_authenticated %}
                    <ul>
                    <li>
                        <a href="{% url 'home:news' %}">News</a>
                    </li>
                    <li>
                        <a href="{% url 'home:housing' %}">Housing</a>
                    </li>
                    <li>
                        <a href="{% url 'home:fees' %}">Pricing</a>
                    </li>
                    <li>
                        <a href="{% url 'home:apply' %}">Apply</a>
                    </li>
                    <li>
                        <a href="{% url 'home:work_order' %}">Work Order</a>
                    </li>
                    <li>
                        <a href="{% url 'home:faq' %}">FAQ</a>
                    </li>
                    {% if user.is_authenticated and user.groups %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% endif %}
                </ul>
                {% endif %}
                {% if not user.is_authenticated %}
                    <ul>
                    <li>
                        <a href="{% url 'home:landing' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'home:housing' %}">Housing</a>
                    </li>
                    <li>
                        <a href="{% url 'home:fees' %}">Pricing</a>
                    </li>
                    <li>
                         <a href="{% url 'home:faq' %}">FAQ</a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'home:register' %}">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="copy-banner">
        <div class="container-fluid">
        <div class="row">
            <div class="col">
                <p id="pageIntro">
                    {% block intro %}
                    {% endblock %}
                </p>
            </div>
            <div class="col" >
                {% if user.is_authenticated %}
                    <p class="text-right" id="userCol">
                        {{ user.username }}
                    </p>
                {% endif %}
            </div>
        </div>

        </div>
    </div>

{% block content %}
{% endblock %}


    <script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}
</body>
</html>

lu_residence_webapp/common/templates/faq/faq.html
{% extends "base.html" %}
{% load static %}

{% block title %}FAQ{% endblock %}

{% block intro %}
    Have a question? Chances are its been answered
{% endblock %}

{% block content %}

    <style>
        #umbrella:hover {
            animation: shake 0.5s;
            animation-iteration-count: infinite;
        }

        @keyframes shake {
            0% { transform: translate(1px, 1px) rotate(0deg); }
            10% { transform: translate(-1px, -2px) rotate(-1deg); }
            20% { transform: translate(-3px, 0px) rotate(1deg); }
            30% { transform: translate(3px, 2px) rotate(0deg); }
            40% { transform: translate(1px, -1px) rotate(1deg); }
            50% { transform: translate(-1px, 2px) rotate(-1deg); }
            60% { transform: translate(-3px, 1px) rotate(0deg); }
            70% { transform: translate(3px, 1px) rotate(-1deg); }
            80% { transform: translate(-1px, -1px) rotate(1deg); }
            90% { transform: translate(1px, 2px) rotate(0deg); }
            100% { transform: translate(1px, -2px) rotate(-1deg); }
        }
        /* this for making responsive but having trouble */
        {% comment %}.responsive {
            width: 100%;
            height: auto;
        }{% endcomment %}
    </style>

<div class="container-fluid">
	<h1>
		<center style="color:blue">
			<img src="{% static 'images/faqs.jpg' %}" alt="questions?????" id="umbrella" class="responsive" width="1000" height="600">
		</center>
	</h1>

	<ol style="color:blue">
		<li><a href="#q1">What is the minimum time (months) I need to register for?</a>
		</li>
		<br />
		<li><a href="#q2">Can I my partner who is not lakehead student live with me at the residence?</a>
		</li>
		<br />
		<li><a href="#q3">Does the residence have laundry facility?</a>
		</li>
		<br />
		<li><a href="#q4">Do you initially support us in buying grocery?</a>
		</li>
		<br />
		<li><a href="#q5">Can I leave the residence mid-way?</a>
		</li>
		<br />
		<li><a href="#q6">Does the residence give any discount for needy student?</a>
		</li>
		<br />
		<li><a href="#q7">Is the residence multicultural?</a>
		</li>
		<br />
		<li><a href="#q8">Can I pray at the residence?</a>
		</li>
		<br />
		<li><a href="#q9">How far is the downtown from the residence?</a>
		</li>
		<br />
		<li><a href="#q10">More Questions?</a>
		</li>
		<br />


		<br />
		<ol style="color:olivedrab">
			<li>
				<a name="q1">What is the minimum time (months) I need to register for?</a>
				<br />
				-> 2 Terms (8 months) for undergraduates and 3 terms (12 months) for graduates.
			</li>
			<br />
			<li>
				<a name="q2">Can I my partner who is not lakehead student live with me at the residence?</a>
				<br />
				-> No, You can't. Only lakehead students are allowed to live permanently.
			</li>

			<li>
				<a name="q3">Does the residence have laundry facility?</a>
				<br />
				-> Yes, it has with plenty of machines.
			</li>
			<br />
			<li>
				<a name="q4">Do you initially support us in buying grocery?</a>
				<br />
				-> Yes, we provide service once a week for the first month.
			</li>

			<li>
				<a name="q5">Can I leave the residence mid-way?</a>
				<br />
				-> You can but you will loose your deposit. So, it is highly discouraged to do so.
			</li>
			<br />
			<li>
				<a name="q6">Does the residence give any discount for needy student?</a>
				<br />
				-> Yes, it has. It is case by case.
			</li>

			<li>
				<a name="q7">Is the residence multicultural?</a>
				<br />
				-> Yes, our residence is highly multicultural.
			</li>
			<br />
			<li>
				<a name="q8">Can I pray at the residence?</a>
				<br />
				-> Yes, you can. You just need to make sure that you don't disturb others.
			</li>

			<li>
				<a name="q9">How far is the downtown from the residence?</a>
				<br />
				-> 10 minutes on drive, 20 min on public transit, 30 min if you walk.
			</li>
			<br />
			<li>
				<a name="q10">More questions?</a>
				<br>
				
			</li>

		</ol>

	</ol>
</div>
{% endblock %}

lu_residence_webapp/common/templates/home/housing.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    CHMSC Housing
{% endblock %}
{% block intro %}
    Welcome to CHMSC Housing
{% endblock %}

{% block content %}

    <div class="container-fluid" >
        <div class="row featurette">

        <h1>WELCOME TO HOUSING!!!</h1>
        <p class="lead">CHMSC University Residence is a bustling environment comprised of 1,200 students from all over the world.<br>

            Accommodations at CHMSC are divided into three living styles: residence halls, apartments and townhouses. Each style provides a unique environment allowing students to experience freedom while receiving the academic and social support that they need to be successful. All of the residences maintain a sense of community, and strive to provide a safe and healthy atmosphere for all of its members.</p>
    </div>

<style>
        form {
            font-size: 13px;
        }
        {#@media only screen and (max-width: 100px) {#}
        {#    #chilling {#}
        {#        display: none;#}
        {#    }#}
        {##}
        #chilling {
            width: inherit;
            height: inherit;
        }

        #slider figure{
        overflow: hidden;
        }
        #slider figure {
        position: relative;
        width: 400%;
        margin: 0;
        left: 0;
        animation: 10s slider infinite;
        }
        #slider figure img {
        width: 20%;
        float: left;
        }
        @keyframes slider{
         0%{
         left:0;
         }
         20% {
         left:0;
         }
         25% {
         left:-100%;
         }
         45% {
         left:-100%;
         }
         50% {
         left:-200%;
         }
         70% {
         left:-200%;
         }
         75% {
         left:-300%;
         }
         95% {
         left:-300%;
         }
        }
            #slider1 figure{
        overflow: hidden;
        }
        #slider1 figure {
        position: relative;
        width: 500%;
        margin: 0;
        left: 0;
        animation: 10s slider infinite;
        }
        #slider1 figure img {
        width: 20%;
        float: right;
        }
            @keyframes slider1{
         0%{
         right:0;
         }
         20% {
         right:0;
         }
         25% {
         right:+100%;
         }
         45% {
         right:+100%;
         }
         50% {
         right:+200%;
         }
         70% {
         right:+200%;
         }
         75% {
         right:+300%;
         }
         95% {
         right:+300%;
         }
        }
    </style>



<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">The Town House <span class="text-muted"></span></h2>
        <p class="lead">Townhouses provide students with the sense of living off-campus but with all the conveniences of living on campus. Our townhouses are reserved for upper-year students with certain units designated as accessible. Optional meal plans are available for your convenience.

All townhouse units are smoke-free.  Smoking is only permitted in designated outside locations.</p>
      </div>
      <div class="col-md-5">
          <div id="slider" >
              <figure>
                  <img src="{% static 'images/th/townhouse.png' %}" alt="townhouse image" width=30% height="350" >
                <img src="{% static 'images/th/4 bedroom exterior.png' %}" alt="townhouse image" width=30% height="350" > 
                  <img src="{% static 'images/th/townhouse accessible.png' %}" alt="townhouse image" width=30% height="350" >
                  <img src="{% static 'images/th/townhouse_room-access-large.png' %}" alt="townhouse image"  width=30%       height="350">
                  
            
              </figure>
          </div>


      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">The Residence Halls</h2>
        <p class="lead">CHMSC University Residence is a bustling environment comprised of 1,200 students from all over the world.

                        Accommodations at CHMSC are divided into three living styles: residence halls, apartments and townhouses. Each style provides a unique environment allowing students to experience freedom while receiving the academic and social support that they need to be successful. All of the residences maintain a sense of community, and strive to provide a safe and healthy atmosphere for all of its members.</p>
      </div>
      <div class="col-md-5 order-md-1">
          <img src="{% static 'images/townhall.png' %}" alt="townhall image" width=100% height="400">
       
      </div>
    </div>
     <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-1">
          
        <h2 class="featurette-heading">The Apartments </h2>
        <p class="lead">North and South apartments are situated between Enclaro Hall Residence and Jomel Residence. These apartments house upper-year students with certain units designated as accessible. Optional meal plans are available for your convenience.</p>
      </div>
        
      <div class="col-md-5 order-md-1">
    
          <div id="slider" >
              <figure>
                  <img src="{% static 'images/ap/1.png' %}" alt="townhouse image" width=30% height="350" >
                <img src="{% static 'images/ap/2.png' %}" alt="townhouse image" width=30% height="350" > 
                  <img src="{% static 'images/ap/3.png' %}" alt="townhouse image" width=30% height="350" >
                  <img src="{% static 'images/ap/4.png' %}" alt="townhouse image"  width=30% height="350">
              </figure>
          </div>


      </div>
    </div>
        
      </div>
    </div>

{% endblock %}

lu_residence_webapp/common/templates/home/landing.html
{% extends "base.html" %}
{% load static %}

{% block title %}Residence News{% endblock %}

{% block intro %}
    News & Events
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <center> <h1><i><b>Welcome to CHMSC University. Home Away From Home!!! </b></i></h1></center>
     	<img src="{% static "images/bg.jpg" %}" alt="Lakehead logo" width="1200px" height="720px">
    </div>
{% endblock %}

lu_residence_webapp/common/templates/workorder/workorder.html
<style>
    {#@import url(https://fonts.googleapis.com/css?family=Roboto:300);#}

    .form {
        max-width: 270px;
    {#font-family: "Lucida Grande", Tahoma, Verdana, sans-serif;#} font-weight: normal;
        line-height: 1.625;
        margin: 8px auto;
        padding-left: 16px;
        z-index: 2;
    }

    h2 {
        font-size: 18px;
        margin-bottom: 8px;
    }

    .img {
        background: url('https://pbs.twimg.com/media/C_q3DXzXoAAjN2M.jpg');
        background-repeat: no-repeat;
        background-size: auto;
        background-size: 100% 100%;
        -webkit-filter: blur(5px);
        -moz-filter: blur(1px);
        -o-filter: blur(1px);
        -ms-filter: blur(1px);
        filter: blur(1px);
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        z-index: -1;
    }

    {#body, html {#}
    {#    height: 100%;#}
    {
    #}#}


    h1 {
        text-align: center;
    }

    .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 20px;
        font-size: 50px;
        border: none;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }


    .flex-container {
        display: flex;
        background: transparent;
    }

    {#.flex-container > div {#}
    {#    background: transparent;#}
    {#    margin: 10px;#}
    {#    padding: 20px;#}
    {#    font-size: 30px;#}
    {#}#}

    h1 {
        text-align: center;
    }

    .dropbtn {
        background-color: #003399;
        color: white;
        padding: 20px;
        font-size: 50px;
        border: none;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #ddd;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }

    .button {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        padding: 14px 40px;
    }

    #work_order_title {
        padding-top: 50px;
    }

</style>

{% extends 'base.html' %}
{% load static %}

{% block title %}
    Work Order
{% endblock %}

{% block intro %}
    Residence Services
{% endblock %}

{% block content %}
    <div class="img"></div>

{#    <div class="flex-container"><br><br>#}
{#    </div>#}
{#    <div class="flex-container">#}
{#    </div>#}

    <div class="container-fluid text-center" id="work_order_title">
        <h1 style="color:#0033cc">Work Order For Residence</h1>
    </div>
    <div class="container-fluid d-flex justify-content-center text-center" id="work_order_title">
        <div class="row" style="background-color: #72b9f4;">
            <div class="col flex-column d-flex justify-content-center text-center">
                <div> {# style="flex-grow: 1" #}
                    <a href="{% url 'home:workorder_townhouse' %}">
                        <img src="{% static 'images/1.png' %}" width="200" height="200">
                    </a>
                </div>
            </div>
            <div class="col flex-column d-flex justify-content-center text-center">
                <div> {# style="flex-grow: 1" #}
                    <a href="{% url 'home:workorder_northres' %}">
                    <img
                        src="{% static 'images/2.png' %}"
                        width="200"
                        height="200">
                    </a>
                </div>
            </div>
            <div class="col flex-column d-flex justify-content-center text-center">
                <div> {# style="flex-grow: 1" #}
                    <a href="{% url 'home:workorder_southres' %}">
                        <img src="{% static 'images/3.png' %}"
                             itemref="southres.html"
                             width="200" height="200">
                    </a>
                </div>
            </div>
            <div class="col flex-column d-flex justify-content-center text-center">
                <div> {# style="flex-grow: 1" #}
                    <a href="{% url 'home:workorder_bartley' %}">
                        <img src="{% static 'images/4.png' %}" width="200" height="200">
                    </a>
                </div>
            </div>
        </div>
    </div>
{#    </div>#}


{% endblock %}